export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const UPDATE_ARCHIVES = 'UPDATE_ARCHIVES';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const UPDATE_TYPE = 'UPDATE_TYPE';
